name: publish
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: check version, and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Install Packages
        run: npm i --legacy-peer-deps
      - name: test
        run: npm run test
      - name: check can npm-publish
        run: npx can-npm-publish
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
